name: CI Workflows

on:
  push:
    branches: [master]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    uses: ./.github/workflows/release.yml
    secrets:
      CHANGESET_TOKEN: ${{ secrets.CHANGESET_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
